config/routes.rb
BotHunter::Application.routes.draw do
  post "pages/create", as: 'add_group'

  resources :profiles

  resources :people, only: [] do
    member do
      get :humanize
      delete :humanize
    end
  end
  resources :groups do
    member do
      get :alive
      get :unknown
      get :bots

      post :delete_bots
      get :report_persons
    end
  end

  resources :campaigns

  resources :pages

  devise_for :users

  resources :users do
    resources :manual_invoices
    resources :groups do
      member do
        get :alive
        get :unknown
        get :bots
      end
    end

    collection do
      get :profile

      post :create_as_admin
      post :send_message_to_all
    end

    member do
      post 'manager'
      post 'approved'
    end
  end

  resources :promocodes

  resources :authorizations
  match '/auth/:provider/callback', to: 'authorizations#create'
  match '/auth/failure', to: 'authorizations#failure'

  root to: 'pages#index'
end

app/models/group.rb
# encoding: utf-8

class Group < ActiveRecord::Base
  extend ActiveRecord::ConnectionAdapters::Quoting

  has_and_belongs_to_many :people, uniq: true
  has_and_belongs_to_many :users, uniq: true

  validates_presence_of :gid
  validates_uniqueness_of :gid
  validates_numericality_of :gid, greater_than: 0

  mount_uploader :cover, GroupCoverUploader

  scope :latest, order('updated_at DESC, created_at DESC')

  def self.alive_for_groups groups_ids
    self.count_for_groups groups_ids, 'alive'
  end

  def self.unknown_for_groups groups_ids
    self.count_for_groups groups_ids, 'unknown'
  end

  def self.bots_for_groups groups_ids
    self.count_for_groups groups_ids, 'bot'
  end

  def self.report_persons gid
    #workbook = RubyXL::Workbook.new
    #serializer = ::SimpleXlsx::Serializer.new("/home/boris/me.xls") do |doc|
    #worbook = WriteExcel.new("/home/boris/me.xls")
    #sheet = worbook.add_worksheet("Живые")
    #sheet.write("Ссылка", "Имя", "Фамилия")

    doc = SimpleXlsx::Serializer.new("test.xlsx")
    sheet = doc.add_sheet("Живые")
    Group.where(gid: gid).first.people.where(state: 'alive').each do |person|
      sheet.add_row(["http://vk.com/id#{person.uid}",person.first_name,person.last_name])
    end
    #workbook.close
   #(sheet,:alive)
    #end

  end

  private

  def self.count_for_groups groups_ids, state
    uncached do
      self.connection.execute(%Q{
        SELECT COUNT(DISTINCT(people.id))
        FROM people
        JOIN groups ON groups.id IN (#{groups_ids.map(&:to_i).join(',')})
        JOIN groups_people ON groups_people.group_id = groups.id AND
          groups_people.person_id = people.id
        WHERE people.state = #{quote state.to_s}
      }).entries.first.values.first.to_i rescue 0
    end
  end
end

app/controllers/groups_controller.rb
# encoding: utf-8

class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_user_id_and_group_id

  authorize_resource

  def index
    groups_ids = @groups.map(&:id)

    @alive_count   = Group.alive_for_groups groups_ids
    @unknown_count = Group.unknown_for_groups groups_ids
    @bots_count    = Group.bots_for_groups groups_ids
  end

  def show
    if current_user.groups_limit <= 0
      @disabled = true
    end

    @alive   = @group.people.where(state: 'alive')
    @bots    = @group.people.where(state: 'bot')
    @unknown = @group.people.where(state: 'unknown')
  end

  def alive
    @persons = @group.people.alive.page params[:page]
    @title = 'Живые пользователи'

    render 'show_persons'
  end

  def bots
    @persons = @group.people.bots.page params[:page]
    @title = 'Боты'

    render 'show_persons'
  end

  def unknown
    @persons = @group.people.unknown.page params[:page]
    @title = 'Сомнительные'

    render 'show_persons'
  end

  def delete_robots
    @group = Group.find params[:id]
    # FIXME: доступ!
    #raise 'Это не ваша группа' unless @group.user_id == current_user.id
    Resque.enqueue BotFilter, @group.gid, params[:login], params[:password]
    render :js => %<$('a[data-gid-to-delete="#{@group.gid}"]').removeClass('danger').addClass('info').text('OK!')>
  rescue
    render :js => %<$('a[data-gid-to-delete="#{@group.gid}"]').removeClass('danger').text(#{$!.to_s.inspect})>
  end


  #def show #gid
  #  @group = Group.first( :conditions {id: params['group_id']})
  #  @alives = @group.persons.where(state: :alive)
  #  @bots = @group.persons.where(state: :bot)
  #  @unknown = @group.persons.where(state: :unknown)
  #end

  def report_persons
    @group = Group.find params[:id]
    blob = StringIO.new('')
    #workbook = WriteExcel.new(blob)

    def make_sheet sheet, sym
      sheet.add_row(["Ссылка", "Имя", "Фамилия"])
      i = 2

      @group.people.where(state: sym).each do |person|
        sheet.add_row(["http://vk.com/id#{person.uid}",person.first_name.encode("utf-8"),person.last_name.encode("utf-8")])
        i+=1
      end
    end

    file_name = "persons-report#{Time.now}"
    serializer = SimpleXlsx::Serializer.new(file_name) do |workbook|
      workbook.add_sheet("Живые") do |alives|
        make_sheet(alives, 'alive')
      end
      workbook.add_sheet("Сомнительные") do |unknown|
        make_sheet(unknown, 'unknown')
      end
      workbook.add_sheet("Боты") do |bots|
        make_sheet(bots, 'bot')
      end
    end

    send_file file_name,
              disposition: 'attachment',
              type: "application/ms-excel",
              filename: "bothunter.xlsx",
              x_sendfile: true
    #workbook.close
    #t.close
  end

  private

  def get_user_id_and_group_id
    if (current_user.admin? || current_user.manager?) && params[:user_id].present?
      @user = User.find params[:user_id]
    else
      @user = current_user
    end

    @groups = @user.groups.latest.scoped
    @group = @groups.find params[:id] if params[:id].present?

    authorize! :read, @groups
    authorize! :read, @group  if params[:id].present?
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.erb
<% alive_count    = group.people.alive.count %>
<% unknown_count  = group.people.unknown.count %>
<% bots_count     = group.people.bots.count %>
<% members_count  = group.members_count %>
<% complete_count = (alive_count + unknown_count + bots_count) %>
<% percentage     = ((complete_count / members_count.to_f) * 100).round rescue 0 %>

<li class="span3">
  <div class="thumbnail">
    <%= image_tag group.cover.thumb.url, class: 'img-260x94' %>

    <div class="caption">
      <h5><%= image_tag '/assets/vk.png' %>&nbsp;<%= link_to "#{group.title}", group %></h5>
      <p><%= truncate group.description, length: 36 %></p>

      <p class="group-count-label">
        <%= link_to alive_group_path(group) do %>
          <i class="icon-user"></i>&nbsp;Живые: <span class="label label-success" style="float: right"><%= number_with_delimiter alive_count %></span>
        <% end %>
      </p>
      <p class="group-count-label">
        <%= link_to unknown_group_path(group) do %>
          <i class="icon-question-sign"></i>&nbsp;Сомнительные: <span class="label label-warning" style="float: right"><%= number_with_delimiter unknown_count %></span>
        <% end %>
      </p>
      <p class="group-count-label">
        <%= link_to bots_group_path(group) do %>
          <i class="icon-fire"></i>&nbsp;Боты: <span class="label label-important" style="float: right"><%= number_with_delimiter bots_count %></span>
        <% end %>
      </p>
      <p class="group-count-label">
        <i class="icon-time"></i>&nbsp;Непроверенные: <span class="label" style="float: right"><%= number_with_delimiter group.people.pending.count %></span>
      </p>
      <p class="group-count-label">
        Всего подписчиков: <span style="float: right"><%= number_with_delimiter members_count %> <!-- (лимит) --></span>
      </p>

      <br>

      <div class="progress <%= complete_count == members_count ? 'progress-success' : 'progress-striped active' %>"> <!-- progress-info progress-success progress-warning progress-danger -->
        <div class="bar" style="width: <%= percentage %>%;"></div>
      </div>

      <p><a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a></p>
    </div>
  </div>
</li>

app/views/groups/_show.html.erb
<!--<div>-->
	<!--<div class="span4">-->
	  <!--<h4>Реальные</h4>-->
	  <!--<% @alive.each do |profile| %>-->
	    <!--<div>-->
	      <!--<a href="http://vkontakte.ru/id<%= profile.uid %>">-->
          <!--<img width="16" height="16" src="<%= profile.photo %>">-->
          <!--"<%= "#{profile.first_name} #{profile.last_name}" %>"-->
	      <!--</a>-->
      <!--</div>-->
    <!--<% end %>-->
  <!--</div>-->
	<!--<div class="span4">-->
	  <!--<h4>-->
	    <!--Неопределенные-->
    <!--</h4>-->
	  <!--<% @unknown.each do |profile| %>-->
	    <!--<div>-->
	      <!--<%= link_to "◀", {:alive_person_id => profile, :group_id => @group}, {:class => "label success real", :id => "pjax", :rel => "twipsy", :title => "Реальный пользователь", :"data-placement" => "left"} %>-->
	      <!--<a href="http://vkontakte.ru/id<%= profile.uid %>">-->
          <!--<img width="16" height="16" src="<%= profile.photo %>">-->
          <!--"<%= "#{profile.first_name} #{profile.last_name}" %>"-->
	      <!--</a>-->
        <!--<%= link_to "▶", {:bot_person_id => profile, :group_id => @group}, {:class => "label important bot", :id => "pjax", :rel => 'twipsy', :title => "Бот", :"data-placement" => "right"} %>-->
      <!--</div>-->
    <!--<% end %>-->
  <!--</div>-->
	<!--<div class="span4">-->
	  <!--<h4>Боты</h4>-->
	  <!--<% @bots.each do |profile| %>-->
	    <!--<div>-->
	      <!--<a href="http://vkontakte.ru/id<%= profile.uid %>">-->
          <!--<img width="16" height="16" src="<%= profile.photo %>">-->
          <!--"<%= "#{profile.first_name} #{profile.last_name}" %>"-->
	      <!--</a>-->
        <!--<a href="#" class="btn danger" data-controls-modal="bots-destroy-modal" data-keyboard="true" data-backdrop="true" data-gid-to-delete="<%= @group.gid %>">Сжечь!</a>-->
      <!--</div>-->
    <!--<% end %>-->
  <!--</div>-->

	<!--<div id="bots-destroy-modal" class="modal hide fade alert-message warning">-->
	  <!--<div class="clearfix">Извините, в бета-версии этот функционал пока недоступен.</div>-->
	  <!--<form method="post" action="#{delete_bots_group_path @group}" data-remote="true">-->
	    <!--<a class="close" href="#">x</a>-->
	    <!--<h2>Удаление роботов из группы</h2>-->
	    <!--<div class="clearfix">Необходимы логин и пароль от аккаунта администратора этой группы.</div>-->
	    <!--<div class="clearfix"><strong>Действие необратимо!</strong></div>-->
	    <!--<div class="clearfix">-->
	      <!--<%= text_field_tag 'login', '', :placeholder => 'логин' %>-->
      <!--</div>-->
	    <!--<div class="clearfix">-->
	      <!--<%= password_field_tag 'password', '', :placeholder => 'пароль' %>-->
      <!--</div>-->
	    <!--<div class="clearfix">-->
	      <!--<%= submit_tag 'Выполнить', class: 'btn danger', onclick: %<$('#bots-destroy-modal').modal('hide'); $('a[data-gid-to-delete="#{@group.gid}"]').removeClass('danger').text('Выполняется...')> %>-->
      <!--</div>-->
    <!--</form>-->
  <!--</div>-->
<!--</div>-->

<div>
  <div class="span4" style="position: absolute; right: 0; top: 0;">
    <a href="/groups/<%= @group.id %>/report_persons" class="btn btn-primary btn-large">Загрузить отчет</a>
  </div>

  <h4>Живые: <%= link_to @alive.count, alive_group_path(@group) %></h4>
  <h4>Сомнительные: <%= link_to @unknown.count, unknown_group_path(@group) %></h4>
  <h4>Боты: <%= link_to @bots.count, bots_group_path(@group) %></h4>
</div>

app/views/groups/index.html.erb
<div class="row">
  <div class="span12">
    <h2>Мои группы</h2>

    <br>

    <ul class="thumbnails">
      <%= render @groups %>
    </ul>

    <br>
  </div>

  <% if @groups.present? &&
      (@alive_count > 0 || @bots_count > 0 || @unknown_count > 0) %>

    <div class="span12">
      <div id="statistics-chart-pie" main-title="Статистика по группам" data-alive="<%= @alive_count %>" data-unknown="<%= @unknown_count %>" data-bots="<%= @bots_count %>" style="max-width: 1000px; height: 400px; margin: 0 auto"></div>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="span8">
    <h4>Добавить группу</h4>
    <%= form_for add_group_path, method: :post do %>
      <div class="clearfix">
        <%= text_field_tag 'group_url', params['group_url'], class: 'span5', placeholder: 'http://vk...' %>
        <% if @disabled %>
          <%= submit_tag 'Добавить', class: 'btn primary small', style: 'margin-left:5px;', disabled: "disabled" %>
        <% else %>
          <%= submit_tag 'Добавить', class: 'btn primary small', style: 'margin-left:5px;' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row" style="position: relative;">
  <div class="span16">
    <div class="row">
      <div class="span4">
        <h2>Группа: <%= @group.title %></h2>
      </div>

      <div class="clearfix"></div>

      <div class="span12">
        <%= render 'show' %>
      </div>
    </div>
  </div>
</div>

app/views/groups/show_persons.html.erb
<h1><%= @title %></h1>

<ul>
  <%= render @persons %>
</ul>

<%= paginate @persons %>