config/routes.rb
BotHunter::Application.routes.draw do
  post "pages/create", as: 'add_group'

  resources :profiles

  resources :people, only: [] do
    member do
      get :humanize
      delete :humanize
    end
  end
  resources :groups do
    member do
      get :alive
      get :unknown
      get :bots

      post :delete_bots
      get :report_persons
    end
  end

  resources :campaigns

  resources :pages

  devise_for :users

  resources :users do
    resources :manual_invoices
    resources :groups do
      member do
        get :alive
        get :unknown
        get :bots
      end
    end

    collection do
      get :profile

      post :create_as_admin
      post :send_message_to_all
    end

    member do
      post 'manager'
      post 'approved'
    end
  end

  resources :promocodes

  resources :authorizations
  match '/auth/:provider/callback', to: 'authorizations#create'
  match '/auth/failure', to: 'authorizations#failure'

  root to: 'pages#index'
end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
  RIGHTS = ['admin', 'manager']
  TYPES = ['all', 'approved', 'unapproved'] + RIGHTS

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :company, :full_name, :phone_number, :message, :promocode_value
  attr_accessible :email, :password, :password_confirmation, :remember_me, :company, :full_name, :phone_number, :message, :promocode_value, :approved, :people_limit, :groups_limit, :rights, as: :admin

  after_create do
    if @promocode_value.present? && self.promocode.present?
      self.promocode.touch
      self.touch
    end
  end

  belongs_to :invoices

  has_one :promocode, dependent: :destroy
  has_many :campaigns, dependent: :destroy
  has_many :oauth_tokens, uniq: true, dependent: :destroy
  has_and_belongs_to_many :groups, uniq: true

  scope :latest, order('created_at DESC, updated_at DESC')
  scope :for_type, -> type {
    if TYPES.include? type.to_s
      case type.downcase
        when 'all'
          self.scoped
        when 'approved'
          self.where(approved: true, rights: nil)
        when 'unapproved'
          self.where(approved: false)
        when 'admin'
          self.where(rights: 'admin')
        when 'manager'
          self.where(rights: 'manager')
      end
    end
  }

  validates_presence_of :full_name, :company, :phone_number
  validate :promocode_value_check

  def phone_number= number
    super Phony.normalize number.gsub(/[^0-9]/, '') rescue nil
  end

  def update_with_password params = {}
    params.delete :current_password
    self.update_without_password params
  end

  def promocode_value_check
    if !self.approved? && self.new_record? && !@promocode_value.nil?
      if self.promocode.nil?
        errors.add(:promocode_value, 'неправильный промокод')
      else
        self.approved       = true
        self.groups_limit   = self.promocode.groups_limit
        self.people_limit   = self.promocode.people_limit
      end
    end
  end

  def admin?
    self.approved? && self.rights.to_s == 'admin'
  end

  def manager?
    self.approved? && self.rights.to_s == 'manager'
  end

  def promocode_value
    self.promocode.try(:code).presence || @promocode_value
  end

  def promocode_value= code
    @promocode_value = code

    if !self.approved? && promo_code = Promocode.find_by_code_and_user_id(code, nil)
      self.promocode = promo_code
    end
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)

    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.registrations.signed_up_but_inactive")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end

    recoverable
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    approved? ? super : I18n.t("devise.registrations.signed_up_but_inactive")
  end

  def token_for provider
    self.oauth_tokens.find_by_provider(provider).token rescue nil
  end
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  before_filter :authenticate_user!

  authorize_resource

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def profile
    @user = current_user

    render 'edit'
  end

  def send_message_to_all
    emails = User.for_type(params[:to]).map(&:email) rescue []
    emails.delete current_user.email

    emails.each do |email|
      MessageToAll.broadcast_message(
        email,
        params[:title],
        params[:message]
      ).deliver!
    end

    redirect_to users_path, notice: 'Письмо отправлено'
  end

  def index
    @users = User.latest.page params[:page]
  end

  def create_as_admin
    @user = User.new params[:user], as: :admin

    if @user.save
      redirect_to users_path, notice: 'Пользователь успешно создан'
    else
      render 'new'
    end
  end

  def manager
    manager = !resource.manager?
    resource.set :_type, (manager ? 'Manager' : 'User')
    render :js => %<$('a[data-manager-id="#{resource.id.to_s}"]')['#{manager ? 'addClass' : 'removeClass'}']('success').text('#{manager ? 'Y' : 'N'}')>
  end

  def approved
    approved = !resource.approved?
    resource.set :approved, approved
    render :js => %<$('a[data-approved-id="#{resource.id.to_s}"]')['#{approved ? 'addClass' : 'removeClass'}']('success').text('#{approved ? 'Y' : 'N'}')>
  end

  def destroy
    @user = User.find params[:id]

    unless user == current_user
      @user.delete

      flash[:notice] = 'Пользователь удален'
    else
      flash[:error] = 'Пользователь не может удалить самого себя!'
    end

    redirect_to users_path
  end

  protected

  def collection
    @users ||= if params[:show].nil?
                 end_of_association_chain.all
               elsif params[:show] == 'inactive'
                 end_of_association_chain.where(['approved != ?', true])
               end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= semantic_form_for @user, url: create_as_admin_users_path do |f| %>
  <%= f.input :full_name, required: false, input_html: { tabindex: 1, autofocus: true } %>
  <%= f.input :email, required: false, input_html: { tabindex: 2 } %>
  <%= f.input :phone_number, required: false, input_html: { tabindex: 3 } %>
  <%= f.input :company, required: false, input_html: { tabindex: 4 } %>
  <%= f.input :password, required: false, input_html: { tabindex: 5 } %>
  <%= f.input :password_confirmation, required: false, input_html: { tabindex: 6 } %>

  <%= f.input :promocode_value, required: false, as: :select, collection: Promocode.available.map { |code| [code.code, code.id] }, input_html: { tabindex: 7 }, label: 'Промо-код (опционально)' %>

  <%= f.input :groups_limit, required: false, as: :string, input_html: { tabindex: 8 } %>
  <%= f.input :people_limit, required: false, as: :string, input_html: { tabindex: 9 } %>

  <%= f.input :rights, required: false, as: :select, collection: User::RIGHTS.map { |right| [I18n.t("titles.rights.#{right}"), right] }, input_html: { tabindex: 10 } %>

  <%= f.input :approved, required: false, as: :boolean, input_html: { tabindex: 11 } %>

  <br>

  <%= f.submit nil, class: 'btn btn-primary', tabindex: 12 %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.id, user_groups_path(user) %></td>
  <td>
    <%= gravatar_image_tag user.email, class: 'gravatar-12', gravatar: { size: 12 } %>
    <%= link_to user.email, user_groups_path(user) %>

    <div class="float-right">
      <% if user.approved? %>
        <% if user.admin? %>
          <span class="label label-important" title="Пользователь является администратором">Администратор</span>
        <% elsif user.manager? %>
          <span class="label label-success" title="Пользователь является менеджером">Менеджер</span>
        <% else %>
          <span class="label label-info" title="Пользователь является подтвержденным">Подтвержденный</span>

          <% unless user.oauth_tokens.present? %>
            <a href="#" title="Пользователь не авторизовался через наше приложение Вконтакте"><i class="icon-remove"></i></a>
          <% end %>
        <% end %>
      <% else %>
        <span class="label label-warning" title="Пользователь ожидает подтверждения">Неподтвержденный</span>
        <% if !user.approved? && user.message.present? %>
          <a href="#" popover-title="<%= user.message %>"><i class="icon-inbox"></i></a>
        <% end %>
      <% end %>
    </div>
  </td>
  <td><%= user.full_name %></td>
  <td><%= number_to_phone user.phone_number, delimiter: ' ' %></td>
  <td><%= user.company %></td>
  <td><%= user.groups.size %></td>
  <td><%= number_with_delimiter user.groups_limit %></td>
  <td><%= number_with_delimiter user.people_limit %></td>
  <td><%= Russian::strftime(user.created_at, '%d %b %H:%M') %></td>
  <td>
    <% unless user == current_user %>
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          Опции
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to user_groups_path(user) do %>
              <i class="icon-list-alt"></i>&nbsp;Группы пользователя
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(user) do %>
              <i class="icon-edit"></i>&nbsp;Изменить настройки
            <% end %>
          </li>

          <li class="divider"></li>

          <li>
            <%= link_to "mailto:#{user.email}?subject=Bothunter" do %>
              <i class="icon-envelope"></i>&nbsp;Отправить на email
            <% end %>
          </li>
        

          <li class="divider"></li>
          <li>
            <%= link_to user, method: 'delete', confirm: 'Вы уверены?' do %>
              <i class="icon-trash"></i>&nbsp;Удалить
            <% end %>
          </li>
        </ul>
      </div>
   <% end %>
  </td>
</tr>

app/views/users/edit.html.erb
<h2>Изменение настроек</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h2>Пользователи</h2>

<br>
<a href="<%= new_user_path %>" data-controls-modal="create-promocode-modal" class="btn btn-primary">Создать нового пользователя</a>
&nbsp;
<a data-toggle="modal" href="#messageDialog" data-controls-modal="create-promocode-modal" class="btn btn-dfault" title="Написать сообщение, которое будет отправлено всем зарегистрированным пользователям">Написать сообщение всем</a>
<br>
<br>

<div class="modal fade" id="messageDialog">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Сообщение пользователям</h3>
  </div>

  <%= form_tag send_message_to_all_users_path do %>
    <div class="modal-body">
      <p>
        <%= label_tag :title, 'Тема' %>
        <%= text_field_tag :title, nil, autofocus: true, tabindex: 1 %>
      </p>

      <p>
        <%= label_tag :message, 'Сообщение' %>
        <%= text_area_tag :message, nil, rows: 8, cols: 45, tabindex: 2 %>
      </p>

      <p>
        <%= label_tag :to, 'Кому' %>
        <%= select_tag :to, options_for_select(User::TYPES.map { |type| [I18n.t("titles.types_to.#{type}"), type] }), tabindex: 3 %>
      </p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Закрыть</a>

      <%= submit_tag 'Отправить', class: 'btn btn-primary', tabindex: 4 %>
    </div>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="id">ID</th>
      <th>Email</th>
      <th>Полное имя</th>
      <th>Телефон</th>
      <th>Компания</th>
      <th title="Количество групп у пользователя в данный момент">Групп</th>
      <th title="Ограничение на колечество групп">Лимит групп</th>
      <th title="Ограничение на колечество людей в группах">Лимит людей</th>
      <th title="Дата регистрации">Регистрация</th>
      <th class="options"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

<%= paginate @users %>

app/views/users/new.html.erb
<h2>Создание нового пользователя</h2>

<%= render 'form' %>