config/routes.rb
BotHunter::Application.routes.draw do
  post "pages/create", as: 'add_group'

  resources :profiles

  resources :people, only: [] do
    member do
      get :humanize
      delete :humanize
    end
  end
  resources :groups do
    member do
      get :alive
      get :unknown
      get :bots

      post :delete_bots
      get :report_persons
    end
  end

  resources :campaigns

  resources :pages

  devise_for :users

  resources :users do
    resources :manual_invoices
    resources :groups do
      member do
        get :alive
        get :unknown
        get :bots
      end
    end

    collection do
      get :profile

      post :create_as_admin
      post :send_message_to_all
    end

    member do
      post 'manager'
      post 'approved'
    end
  end

  resources :promocodes

  resources :authorizations
  match '/auth/:provider/callback', to: 'authorizations#create'
  match '/auth/failure', to: 'authorizations#failure'

  root to: 'pages#index'
end

app/models/promocode.rb
class Promocode < ActiveRecord::Base
  attr_accessor :email_to

  belongs_to :user

  validates_numericality_of :groups_limit, greater_than: 0
  validates_numericality_of :people_limit, greater_than: 0
  validates_email_format_of :email_to, :if => proc { |record| record.email_to.present? }
  validates :code, uniqueness: true, presence: true

  scope :available, where(user_id: nil)
  scope :latest, order('created_at DESC, updated_at DESC')

  ##before_create :multiply
  #
  #
  ##attr_accessor :promocodes_count # reader needed for form generation

#protected
#  def multiply
#    count = @promocodes_count.to_i
#    
#    if count > 1
#      count = count.pred
#
#      attrs = self.attributes
#      attrs.delete :_id
#      attrs.delete '_id'
#      attrs.delete :id
#      attrs.delete 'id'
#
#      count.times{ Promocode.create attrs }
#    end
#  end
end

app/controllers/promocodes_controller.rb
# encoding: utf-8

class PromocodesController < ApplicationController
  before_filter :authenticate_user!

  authorize_resource

  def index
    @promocodes = Promocode.latest.page params[:page]
  end

  def new
    respond_to do |format|
      format.html { @promocode = Promocode.new code: random_words_string }
      format.js
    end
  end

  def create
    @promocode      = Promocode.new params[:promocode]
    @promocode.code = random_words_string unless @promocode.code.present?

    if @promocode.save
      redirect_to promocodes_path, notice: 'Промо-код успешно создан'
    else
      render 'new'
    end
  end

  def destroy
    @promocode = Promocode.find params[:id]
    @promocode.delete

    redirect_to promocodes_path, notice: 'Промо-код удален'
  end
end

app/helpers/promocodes_helper.rb
module PromocodesHelper
end

app/views/promocodes/_promocode.html.erb
<tr>
  <td><%= promocode.id %></td>
  <td>
    <% if promocode.user.nil? %>
      <span class="badge badge-success">
        <%= promocode.code %>
      </span>

      <div class="float-right">
        <%= raw clippy promocode.code %>
      </div>
    <% else %>
      <span class="badge"><%= promocode.code %></span>
    <% end %>
  </td>
  <td><%= number_with_delimiter promocode.groups_limit %></td>
  <td><%= number_with_delimiter promocode.people_limit %></td>
  <td>
    <% if promocode.user.nil? %>
      <span class="label label-success">нет</span>
    <% else %>
      <%= gravatar_image_tag promocode.user.email, class: 'gravatar-12', gravatar: { size: 12 } %>
      <a href="<%= user_path promocode.user %>"><%= promocode.user.full_name %> (<%= promocode.user.email %>)</a>
    <% end %>
  </td>
  <td>
    <div class="btn-group">
      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        Опции
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <% if promocode.user.nil? %>
          <li>
            <a href='#'><i class="icon-envelope"></i>&nbsp;Отправить на email</a>
          </li>
          <li class="divider"></li>
        <% end %>

        <li>
          <%= link_to promocode, method: 'delete', confirm: 'Вы уверены?' do %>
            <i class="icon-trash"></i>&nbsp;Удалить
          <% end %>
        </li>
      </ul>
    </div>
  </td>
</tr>

app/views/promocodes/index.html.erb
<h2>Промо-коды</h2>

<br>
<a href="<%= new_promocode_path %>" data-controls-modal="create-promocode-modal" class="btn btn-primary">Создать новый промо-код</a>
<br>
<br>

<% if @promocodes.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="id">ID</th>
        <th>Код</th>
        <th>Группы, шт.</th>
        <th>Пользователи, шт.</th>
        <th>Используется</th>
        <th class="options"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @promocodes %>
    </tbody>
  </table>
<% end %>

<%= paginate @promocodes %>

app/views/promocodes/new.html.erb
<%= semantic_form_for @promocode do |f| %>
  <h2>Создание промо-кодов</h2>

  <div class="clearfix">
    Необходимо указать количество групп и страниц, которыми будет ограничиваться пользователь, зарегистрировавшийся по промо-коду.
  </div>

  <%= f.input :groups_limit, as: :string, required: false, input_html: { autofocus: true, tabindex: 1 } %>
  <%= f.input :people_limit, as: :string, required: false, input_html: { tabindex: 2 } %>
  <%= f.input :email_to, as: :email, required: false, input_html: { tabindex: 3 } %>
  <%= f.input :code, as: :string, required: false, input_html: { tabindex: 4 } %>
  <div>
    <%= link_to new_promocode_path, remote: true do %>
      <i class="icon-refresh"></i>&nbsp;Обновить промо-код
    <% end %>
  </div>

  <br>
  <%= f.submit 'Создать', class: 'btn btn-primary', tabindex: 5 %>
<% end %>

app/views/promocodes/new.js.erb
$('#promocode_code').val("<%= escape_javascript random_words_string %>");