config/routes.rb
BotHunter::Application.routes.draw do
  post "pages/create", as: 'add_group'

  resources :profiles

  resources :people, only: [] do
    member do
      get :humanize
      delete :humanize
    end
  end
  resources :groups do
    member do
      get :alive
      get :unknown
      get :bots

      post :delete_bots
      get :report_persons
    end
  end

  resources :campaigns

  resources :pages

  devise_for :users

  resources :users do
    resources :manual_invoices
    resources :groups do
      member do
        get :alive
        get :unknown
        get :bots
      end
    end

    collection do
      get :profile

      post :create_as_admin
      post :send_message_to_all
    end

    member do
      post 'manager'
      post 'approved'
    end
  end

  resources :promocodes

  resources :authorizations
  match '/auth/:provider/callback', to: 'authorizations#create'
  match '/auth/failure', to: 'authorizations#failure'

  root to: 'pages#index'
end

app/views/layouts/_topbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner fill">
    <div class="container">
      <%= link_to "Бот-хантер", root_path, class: 'brand' %>

      <ul class="nav">
        <%= link_highlight 'Мои группы', groups_path %>

        <% if can? :manage, Manager %>
          <%= link_highlight 'Пользователи', users_path %>
          <%= link_highlight 'Промо-коды', promocodes_path %>
        <% end %>

        <%= link_highlight 'Профиль', profile_users_path %>
        <%= link_highlight 'FAQ', '#' %>
      </ul>

      <ul class="nav secondary-nav pull-right">
        <li><%= link_to "Групп: #{current_user.groups_limit}", root_path %>
        <!--<li class="menu" data-dropdown="dropdown">-->
          <!--<a href="#" class="dropdown-toggle">Групп: <%#= current_user.groups_limit %></a>-->

          <!--<ul class="menu-dropdown">-->
            <!--<li><%#= link_to "5 групп, 10.00 денег", "/robokassa/start?#{RobokassaMerchant.signed_start_params(5, 10, current_user)}" %></li>-->
            <!--<li><%#= link_to "10 групп, 17.50 денег", "/robokassa/start?#{RobokassaMerchant.signed_start_params(10, 17.5, current_user)}" %></li>-->
          <!--</ul>-->
        <!--</li>-->
        <li><%= link_to "Выйти", destroy_user_session_path, method: 'delete' %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bothunter</title>

    <link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user %>
      <%= render "layouts/topbar" %>
    <% end %>

    <div class="container">
      <div class="toolbar-free-space"></div>

      <% if flash.present? %>
        <% flash.each do |type, message| %>
          <%= content_tag :div, class: "alert alert-#{type}" do %>
            <%= link_to 'x', '#', class: 'close', 'data-dismiss' => 'alert' %>
            <strong><%= t("alerts.#{type}") %></strong> <%= message %>
          <% end %>
        <% end %>

        <div class="toolbar-free-space"></div>
      <% end %>

      <div class="content">
        <%= yield %>
      </div>

      <footer class="footer">
        <div class="container">
          <ul>
            <li>
              ©&nbsp;<a href="http://myhotspot.ru" target="_blank">Hot Spot</a>&nbsp;2011-<%= COPYRIGHT_YEAR %>
            </li>
            <li>
              <a href="mailto:bothunter@myhotspot.ru?subject=Bothunter">Связаться с нами</a>
            </li>
          </ul>
        </div>
      </footer>
    </div>

    <script>
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-29877589-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>